name: Do something Workflow
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build-n-merge-job:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Make some change.
        run : |
          ps -ef | grep something > output.txt
      - name: See status
        run: git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Index updated via github workflow."
          title: "Automated Index Update PR from call workflow."
