name: Do something Workflow
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build-n-merge-job:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Make some change.
        run : |
          ps -ef | grep something > output.txt
      - name: See status
        run: git status
      - name: check for changes
        run: |
          if git diff --exit-code; then
              echo "No code changes."
          else
              echo "Commiting the code change."
              git config --global user.email "rakesh.bangera@saiesha.us"
              git config --global user.name "Rakesh Bangera"              
              git commit -am "Added something."
              git push
          fi
