name: Tryout Workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        run: echo "Initializing.."
      - name: Build
        run: |
          echo "Building.."
          echo "Done!"
  deploy-job:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: check for changes
        run: |
          if git diff --exit-code; then
              echo "No code changes."
          else
              echo "Code has changed."
          fi


