name: Tryout Workflow
on: 
  workflow_dispatch:
  pull_request:
    branches: ['main', 'staging', 'development']
    types: ['opened', 'closed']


jobs:
  build-n-test-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        run: echo "Initializing.."
      - name: Build
        run: |
          echo "Building.."
          echo "Done!"
      - name: Print github refs
        run: echo 'refs = ${{github.ref}}'
  update-job:
    runs-on: ubuntu-24.04
    needs: build-n-test-job
    steps:
      - name: Update
        run: |
          echo "Updating.."
          echo "Done!"    
  deploy-job:
    needs: update-job
    runs-on: ubuntu-24.04
    if: |
         ( github.event.pull_request.merged == true && github.event.pull_request.title != 'Automated Index Update PR from main workflow.')
    steps:
      - uses: actions/checkout@v4
      - name: Print PR
        run: echo '${{toJSON(github.event.pull_request)}}'
      - name: Make some change.
        if: github.ref == 'refs/heads/staging'
        run : |
          ps -ef | grep something > output.txt
      - name: See status
        run: git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Index updated via github workflow."
          title: "Automated Index Update PR from main workflow."
      - name: Current date time
        uses: kaven-universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY_MM_DD_HH_mm_ss_SSS"
        id: current-date-time
      - name: Print Current date and time.
        run: echo "${{ steps.current-date-time.outputs.time }}"  
      - name: Only if development
        if: github.ref == 'refs/heads/development'
        run: echo "Only if development."
      - name: Only if staging
        if: github.ref == 'refs/heads/staging'
        run: echo "Only if staging."
      - name: Only if staging
        if: github.ref == 'refs/heads/staging' && github.event.pull_request.title != 'Automated Index Update PR from call workflow.'
        run: echo "Only if staging and PR not call workflow."
        
      

      


