name: Tryout Workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        run: echo "Initializing.."
      - name: Build
        run: |
          echo "Building.."
          echo "Done!"
  deploy-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy
        run: |
          git status 
          echo "Deploy."
      - name: Some output
        id : cmdOutput  
        run: |
          echo "CMD_OUTPUT=$(git status)" >> $GITHUB_OUTPUT 
      - name: Show the output
        run: echo "${{ toJSON(steps.cmdOutput.outputs) }}"

